### ISSUE TITLE
Starting a level from the Scene in the editor doesn't load it properly

### ISSUE THREAD

**Issue by CAD97** [Podshot/TwoTogether#11]
I suspect this is a by-product of the work you've done with dynamic levels, and the levels are loading using a different protocol now. It would be best to either set up the scenes such that they load in the level correctly or delete them if they are not needed.

However, for testing purposes it is good to be able to start at any level, so a way to start at any level should be built into whatever level system you set up.

In the meantime:
WORKAROUND:
Play up to the level you need to test from the Main Menu, and it will work fine.

**Comment by Podshot** [comment]
You can load any level by changing line 38 in Scripts/LevelUtils/LoadLevel.cs to the filename of the level, without the .json extension. A level selection menu is planned, but may not happen until after the next alpha build
