### ISSUE TITLE
Stuck on flat terrain

### ISSUE THREAD

**Issue by CAD97** [Podshot/TwoTogether#9]
... when moving between to colliders for the floor. (As acknowledged in the first alpha build)
## What Causes This

When moving between level geometry, there is a seam in the collision detection as the levels are currently laid out. As you might know, seams in collision detection are often vulnerability points in a game's physics. In this case, even if two colliders line up perfectly (and according to Unity's own units and a little math, they do in my test case), this seam prevents an actor moving using physics without any upward velocity from passing.

Why? I don't know. Physics engines are magic and we try not to mess them up.
## Possible Fixes

The simplest fix is very simple. Just make sure that the level design never includes two colliders at the same level, but rather one horizontal platform on top that the actors will travel across. The rest of the geometry can be set up however the level designer cares, though keeping in mind every seam carries with it the risk of invisible tiny not-really-there-but-still-cling-able seams in the collision detection.

The other fix is a good deal more difficult but better in the long run in both performance and game design principle: only have one complex polygon that is the collision detection for level geometry. Unless a collider moves, Unity does build them all into an agglomerated static collider anyway, minimizing the benefits of doing it manually to performance minimal, but in this case you can see where we would benefit.

Apparently when Unity builds the static geometry of the level, seams in collision detection are not built flat, and as such the actors get caught. If we set up manually, or a system to automatically, the level geometry as one Polygon Collider 2D (or similar) (And additional ones for any floating geometry, of course), rather than many smaller Box Colliders, then all edges of geometry are guaranteed to be as we want them -- perfectly flat between our defined corners.

The last possible fix is the most "hack-y" off them all -- set up a "step size" for the actors. If they run into a seam, just give them a bit of upward velocity to clear it. Let me stress that I would not recommend this setup, as it is liable to break at the touch of a hair. That is, unless we can find an actual Step Size setting somewhere in the Unity settings that would apply to this (as opposed to pathfinding, which I know has one).
## In Conclusion

Character physics are hard, man. That's why most people either use a character controller built by the engine or provided from a 3rd party.

**Comment by CAD97** [comment]
The write-up has been finished.

Well, who knew "when I'm not half-asleep" and going to actually write this would turn out to be in exactly about 24 hours. (What a strange phrase "exactly about" is.)

**Comment by Podshot** [comment]
Have a look at commit 8e977e3, I replaced all terrain BoxCollider2Ds with EdgeCollider2Ds. It seemed to fix the issue, but it may turn out to be only a temporary fix.

**Comment by CAD97** [comment]
Well, it works. I have no idea why it does, but it works. If I knew the ins and outs of the Unity Physics engine, I might be able to say. But my gut reaction is "it shouldn't work like this."

But hey, it works, and it's simple (enough). All the more power to you for this fix.

And here's my guess as to what is happening: magic.
